name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analyze code with pylint
        run: |
          pylint $(git ls-files '*.py')

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'
      - name: Run tests with coverage
        uses: dima-engineer/pytest-reporter@v1.1.3
        with:
          cov-omit-list: test/*,setup.py
          cov-threshold-total: 90
  build_wheels:
    name: Build wheel
    if: startsWith(github.ref, 'refs/tags/')
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build wheel
        run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
  deploy:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - uses: actions/checkout@v2
      - name: Upload to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: ortega2247/pypi-upload-action@master
        with:
          user: ${{ secrets.pypi_token }}
          password: ${{ secrets.pypi_password }}
