name: Pylint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analyze code with pylint
        run: |
          pylint $(git ls-files '*.py')

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'
      - name: Run tests with coverage
        uses: dima-engineer/pytest-reporter@v1.1.3
        with:
          cov-omit-list: test/*,setup.py
          cov-threshold-total: 90

